// SPDX-License-Identifier: MIT
// Not pinned to an exact version like the rest of contracts/: this file imports
// SolvencyHonkVerifier.sol, whose own internal pragma (^0.8.27) forces the whole import
// graph to compile under one shared solc version — see the matching override in
// hardhat.config.js, which resolves that to 0.8.30/cancun for both files together.
pragma solidity ^0.8.24;

import {ISolvencyVerifier} from "../interfaces/ISolvencyVerifier.sol";
import {SolvencyHonkVerifier} from "./generated/SolvencyHonkVerifier.sol";

/// @notice Adapter between Latens's protocol-level `ISolvencyVerifier` interface and the
/// real, machine-generated `SolvencyHonkVerifier` (Barretenberg's UltraHonk EVM verifier for
/// circuits/solvency).
///
/// @dev The calldata mapping here is not guesswork — it's read directly from
/// `BaseZKHonkVerifier.verify` in the generated file and confirmed against a real proof:
/// `publicInputs` is exactly the circuit's own declared public inputs (5, matching
/// `ISolvencyVerifier`'s layout) — NOT the file's `NUMBER_OF_PUBLIC_INPUTS` (13). That larger
/// number includes `PAIRING_POINTS_SIZE` (8) additional field elements that are a BN254
/// pairing/aggregation object embedded INSIDE the proof bytes themselves, extracted
/// internally by the verifier (`ZKTranscriptLib.loadProof`) — never supplied by the caller.
/// `proof` is passed straight through as bb produces it, unmodified. See
/// `test/SolvencyHonkVerifier.integration.test.js`, which verifies (and rejects a tampered
/// public input on) a real proof generated by `circuits/solvency`, and
/// `test/LatensPool.realVerifier.integration.test.js`, which drives a real `LatensPool.borrow`
/// call through this exact adapter using that same real proof.
contract NoirSolvencyVerifier is ISolvencyVerifier {
    SolvencyHonkVerifier public immutable honkVerifier;

    constructor(SolvencyHonkVerifier honkVerifier_) {
        honkVerifier = honkVerifier_;
    }

    function verifySolvency(bytes calldata proof, uint256[] calldata publicInputs) external view returns (bool) {
        bytes32[] memory honkPublicInputs = new bytes32[](publicInputs.length);
        for (uint256 i = 0; i < publicInputs.length; i++) {
            honkPublicInputs[i] = bytes32(publicInputs[i]);
        }
        return honkVerifier.verify(proof, honkPublicInputs);
    }
}
