import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Hand-ordered rather than autogenerated: the reading order here (privacy model before
// proofs before circuits before contracts) is deliberate and doesn't match alphabetical
// or filesystem order.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    "index",
    "privacy-model",
    "proofs",
    "circuits",
    "contracts",
    "economics",
    "assets",
    "viewing-keys",
    "status",
    "deployment",
  ],
};

export default sidebars;
