import deployment from "./deployment.json";
import type { Abi } from "viem";

// Generated by script/deployLocal.js against the local Hardhat node — see
// contracts/README.md before pointing this at anything else.
export const latensPool = {
  address: deployment.contracts.LatensPool.address as `0x${string}`,
  abi: deployment.contracts.LatensPool.abi as Abi,
};

export const assetRegistry = {
  address: deployment.contracts.AssetRegistry.address as `0x${string}`,
  abi: deployment.contracts.AssetRegistry.abi as Abi,
};

export const priceOracle = {
  address: deployment.contracts.MockPriceOracle.address as `0x${string}`,
  abi: deployment.contracts.MockPriceOracle.abi as Abi,
};

export const erc20Abi = deployment.contracts.MockERC20.abi as Abi;

export type TokenSymbol = keyof typeof deployment.tokens;

export const tokens = deployment.tokens as Record<
  string,
  { address: `0x${string}`; symbol: string; decimals: number; assetId: number }
>;

export const tokenList = Object.values(tokens);
